### ISSUE TITLE
fix vecRestoreArray

### ISSUE THREAD

**Issue by ocramz** [ocramz/petsc-hs#4]
`vecGetArray` in Raw/PutGet works fine, but its dual `vecRestoreArray` does not seem to update the C-side Vec.

This behavior can be observed by running `t3`, `t4` or `t5` in TestMain2.hs

**Comment by ocramz** [comment]
@bkaestner , have you by chance managed to build ? Sorry to bother you, but I could really use some help on this issue; I've been stuck on it for some time now. 

To recap, the low-level signatures are in Raw/InlineC.hs and are marked with a single apex, whereas Raw/PutGet.hs contains the mid-level functions used in the examples. 

Thank you in advance

**Comment by bkaestner** [comment]
Sorry, still just on Windows. Need to install a VM and PETSc.

**Comment by ocramz** [comment]
FIXED: 

```
vecGetVector :: Vec -> IO (V.Vector PetscScalar_)
vecGetVector v = do
  p <- vecGetArrayPtr v
  pf <- newForeignPtr_ p
  V.freeze (VM.unsafeFromForeignPtr0 pf len)
   where
     len = vecSize v

vecRestoreVector :: Vec -> V.Vector PetscScalar_ -> IO ()
vecRestoreVector v w = do
  p <- vecGetArrayPtr v
  pf <- newForeignPtr_ p
  V.copy (VM.unsafeFromForeignPtr0 pf len) w
  vecRestoreArrayPtr v p
    where
     len = vecSize v
```

and

```
withVecGetVectorOverwrite ::
  Vec ->
  (V.Vector PetscScalar_ -> V.Vector PetscScalar_) ->
  IO ()
withVecGetVectorOverwrite v modify = do
  x <- vecGetVector v
  let y = modify x
  vecRestoreVector v y
```
